version: '3.8'
services:
  health-api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    environment:
      - PORT=8080
      - AWS_REGION=ap-south-1
      - DB_PORT=5432
      - DB_NAME=postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3