apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
  namespace: health-app-dev  # Will be replaced by deployment workflow
  labels:
    app: health-api
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
        environment: dev
    spec:
      containers:
      - name: health-api
        image: arunprabusiva/health-api:latest  # Will be replaced by deployment workflow
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: AWS_REGION
          value: "ap-south-1"
        - name: COGNITO_USER_POOL_ID
          valueFrom:
            secretKeyRef:
              name: health-api-secrets
              key: cognito-user-pool-id
        - name: COGNITO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: health-api-secrets
              key: cognito-client-id
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: health-api-secrets
              key: db-host
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: health-api-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: health-api-secrets
              key: db-password
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"