# Create secrets using kubectl command instead of this file for security
# kubectl create secret generic health-api-secrets \
#   --from-literal=cognito-user-pool-id=ap-south-1_HnfbmsE7T \
#   --from-literal=cognito-client-id=1u4gvhaa2sr4jisqd73v85jdqd \
#   --from-literal=db-host=healthapidb.ct4cmoguswkb.ap-south-1.rds.amazonaws.com \
#   --from-literal=db-user=postgres \
#   --from-literal=db-password=PgbQ232Tg

apiVersion: v1
kind: Secret
metadata:
  name: health-api-secrets
type: Opaque
data:
  # Base64 encoded values - DO NOT commit real values to git
  cognito-user-pool-id: <base64-encoded-value>
  cognito-client-id: <base64-encoded-value>
  db-host: <base64-encoded-value>
  db-user: <base64-encoded-value>
  db-password: <base64-encoded-value>