apiVersion: v1
kind: Service
metadata:
  name: health-api-service
  labels:
    app: health-api
spec:
  selector:
    app: health-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP