name: Pull Request Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: |
        cd tests
        npm ci
        npm test
        
    - name: Check if version is release version
      id: check-version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        if [[ $VERSION == *"-SNAPSHOT"* ]]; then
          echo "Version $VERSION still contains SNAPSHOT suffix"
          echo "::error::Please run 'npm run version:release' to remove SNAPSHOT suffix before merging to main"
          exit 1
        else
          echo "Version $VERSION is a release version"
        fi