name: Feature Branch Build

permissions:
  contents: read

on:
  push:
    branches: ['fet-*']

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Extract branch name
      id: extract-branch
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        FEATURE_NAME=${BRANCH_NAME#fet-}
        echo "feature-name=$FEATURE_NAME" >> $GITHUB_OUTPUT
      
    - name: Extract version
      id: extract-version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        SNAPSHOT_VERSION="${VERSION}-${TIMESTAMP}"
        echo "snapshot-version=$SNAPSHOT_VERSION" >> $GITHUB_OUTPUT
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/health-api:${{ steps.extract-version.outputs.snapshot-version }}
          ${{ secrets.DOCKER_USERNAME }}/health-api:${{ steps.extract-branch.outputs.feature-name }}-snapshot
        platforms: linux/amd64,linux/arm64